# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calmodulin Model Wrapper Function (exported to R)
#'
#' This function calls the internal C++ simulator function to simulate the Calmodulin model. 
#' @param
#' @return
#' @examples
#' sim_calmodulin()
#' @export
sim_calmodulin <- function(param_input_df, param_sim_params, param_model_params) {
    .Call('_CalciumModelsLibrary_sim_calmodulin', PACKAGE = 'CalciumModelsLibrary', param_input_df, param_sim_params, param_model_params)
}

#' CamKII Model Wrapper Function (exported to R)
#'
#' This function calls the internal C++ simulator function to simulate the CamKII model. 
#' @param
#' @return
#' @examples
#' sim_camkii()
#' @export
sim_camkii <- function(param_input_df, param_sim_params, param_model_params) {
    .Call('_CalciumModelsLibrary_sim_camkii', PACKAGE = 'CalciumModelsLibrary', param_input_df, param_sim_params, param_model_params)
}

#' PKC Model Wrapper Function (exported to R)
#'
#' This function calls the internal C++ simulator function to simulate the PKC model. 
#' @param
#' @return
#' @examples
#' sim_pkc()
#' @export
sim_pkc <- function(param_input_df, param_sim_params, param_model_params) {
    .Call('_CalciumModelsLibrary_sim_pkc', PACKAGE = 'CalciumModelsLibrary', param_input_df, param_sim_params, param_model_params)
}

